        !COMPILER-GENERATED INTERFACE MODULE: Thu Jul 28 16:03:25 2016
        MODULE ELAPSED_TIME__genmod
          INTERFACE 
            FUNCTION ELAPSED_TIME(C1,C2)
              INTEGER(KIND=4) :: C1
              INTEGER(KIND=4) :: C2
              REAL(KIND=8) :: ELAPSED_TIME
            END FUNCTION ELAPSED_TIME
          END INTERFACE 
        END MODULE ELAPSED_TIME__genmod
