        !COMPILER-GENERATED INTERFACE MODULE: Thu Jul 28 16:03:25 2016
        MODULE QUICKSORT__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE QUICKSORT(LIST,LO,HI)
              REAL(KIND=8), INTENT(INOUT) :: LIST(*)
              INTEGER(KIND=4), INTENT(IN) :: LO
              INTEGER(KIND=4), INTENT(IN) :: HI
            END SUBROUTINE QUICKSORT
          END INTERFACE 
        END MODULE QUICKSORT__genmod
