        !COMPILER-GENERATED INTERFACE MODULE: Thu Jul 28 16:03:25 2016
        MODULE SELECTION_SORT__genmod
          INTERFACE 
            SUBROUTINE SELECTION_SORT(LIST,N)
              REAL(KIND=8) :: LIST(:)
              INTEGER(KIND=4) :: N
            END SUBROUTINE SELECTION_SORT
          END INTERFACE 
        END MODULE SELECTION_SORT__genmod
